# Generated by Django 5.1.2 on 2024-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_documentembedding_remove_userfeedback_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airesponse",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="airesponse",
            name="response_time",
        ),
    ]
